{% set name = "eslint-config-prettier" %}
{% set version = "8.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prettier/eslint-config-prettier/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 476cc461d077997f328fb3207b7c0720bdc27a43574789339a49f9563cf4f67f

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - test -d $PREFIX/lib/node_modules/eslint-config-prettier  # [unix]
    - if not exist %LIBRARY_INC%\lib\node_modules\eslint-config-prettier exit 1  # [win]

about:
  home: https://github.com/prettier/eslint-config-prettier
  license: MIT
  license_file:
    - LICENSE
    - build/ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
    - jens-ox
